### ISSUE TITLE
Pyannote's latest version is incompatible

### ISSUE THREAD

**Issue by M-Rochat** [GuillaumeRochette/psifx#3]
### Tested versions
0.0.2
### System information

Ubuntu 22.04.2 LTS 
### Issue description
Concerning psifx audio diarization pyannote inference tool,
I am unable to use the newest version pyannote-speaker-diarization-3.1 both in the code and command line.
The checkpoint_path should be "pyannote/speaker-diarization-3.1" however it is parsed as

`checkpoint_path=f"pyannote/speaker-diarization@{model_name}"`

with @ instead of -

**Comment by GuillaumeRochette** [comment]
Thanks for creating this issue and making the PR :)
I will add more docs and other things next weekend, and publish a new release with the changes introduced by the PR.
In the meantime you can always update your installation of `psifx` with:
```bash
pip install git+https://github.com/GuillaumeRochette/psifx.git@7289e2e
```
